title: DataMines
description: AI Algorithms - Satellite data - Geospatial Intelligence.
show_downloads: false
is_project_page: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
exclude: [gems]
github:
  scholar_url: https://scholar.google.dk/citations?user=o60s11UAAAAJ&hl=da
  another_url: datamines.dk